import { MS_PER_SEC, SECONDS_PER_MINUTE } from '@/constants/units';

/**
 * Only one message (all types, inc. whisper) will be handled per these ticks.
 */
export const CHAT_MESSAGE_PER_TICKS_LIMIT = 12;

export const CHAT_MUTE_TIME_MS = 10 * SECONDS_PER_MINUTE * MS_PER_SEC;

export const CHAT_SUPERUSER_MUTE_TIME_MS = 60 * SECONDS_PER_MINUTE * MS_PER_SEC;

/**
 * To use /votemute player must play (not spectate, not stay) at least this time duration.
 */
export const CHAT_MIN_PLAYER_PLAYTIME_TO_VOTEMUTE_MS = 60 * MS_PER_SEC;

// https://github.com/web-mech/badwords/blob/master/lib/lang.json
export const CHAT_HATE_SPEECH_FORBIDDEN_PHRASES = [
  'b!+ch',
  'b!tch',
  'b17ch',
  'b1tch',
  'bassterds',
  'bastard',
  'bastard',
  'bastards',
  'bastardz',
  'basterds',
  'basterdz',
  'bi+ch',
  'bi7ch',
  'biatch',
  'bitch',
  'bitches',
  'c0ck sucker',
  'c0ck-head',
  'c0ck-sucker',
  'c0ck',
  'c0ckhead',
  'c0ckhead',
  'c0cksucker',
  'c0k',
  'chink',
  'cock sucker',
  'cock-head',
  'cock-sucker',
  'cock',
  'cockhead',
  'cocksucker',
  'cum',
  'cunt',
  'dego',
  'dick',
  'dickhead',
  'dyke',
  'enculer',
  'enema',
  'fag',
  'fag1t',
  'faget',
  'fagg0t',
  'fagg1t',
  'faggit',
  'faggot',
  'fagit',
  'fags',
  'fagz',
  'faig',
  'faigs',
  'fcuk u',
  'fcuk you',
  'fuck u',
  'fuck you',
  'fuk u',
  'fuk you',
  'gook',
  'gypsy',
  'h00r',
  'h0ar',
  'h0r',
  'h0re',
  'hail hitler',
  'heil hitler',
  'hoar',
  'hoer',
  'hoor',
  'hoore',
  'hore',
  'hui',
  'huy',
  'injun',
  'jap',
  'jizz',
  'kike',
  'knob',
  'kraut',
  'kuk',
  'kuksuger',
  'kunt',
  'kurac',
  'kurwa',
  'motha fucker',
  'motha fuker',
  'motha fukkah',
  'motha fukker',
  'mother fucker',
  'mother fucker',
  'mother fukah',
  'mother fuker',
  'mother fukkah',
  'mother fukker',
  'mother-fucker',
  'motherfucker',
  'muschi',
  'mutha fucker',
  'mutha fukah',
  'mutha fuker',
  'mutha fukkah',
  'mutha fukker',
  'n1ga',
  'n1gga',
  'n1gger',
  'n1gger',
  'n1gr',
  'n1gur',
  'ngga',
  'ngr',
  'niga',
  'niger',
  'niger',
  'nigga',
  'nigr',
  'nigur',
  'niiger',
  'niigr',
  'p1zda',
  'pizda',
  'pusse',
  'pusse',
  'pussee',
  'pussy',
  'pussy',
  'puto',
  'sieg hail',
  'sieg heil',
  'skanck',
  'skank',
  'skankee',
  'skankey',
  'skanks',
  'skanky',
  'slut',
  'slut',
  'sluts',
  'slutty',
  'slutz',
  'spic',
  'splooge',
  'suka',
  'twat',
  'wh00r',
  'wh0re',
  'whoar',
  'whore',
  'whore',
];
