export const BROADCAST_CHAT_PUBLIC = 'BROADCAST_CHAT_PUBLIC';

export const BROADCAST_CHAT_SAY = 'BROADCAST_CHAT_SAY';

export const BROADCAST_CHAT_SAY_REPEAT = 'BROADCAST_CHAT_SAY_REPEAT';

export const BROADCAST_CHAT_SERVER_PUBLIC = 'BROADCAST_CHAT_SERVER_PUBLIC';

export const BROADCAST_CHAT_SERVER_TEAM = 'BROADCAST_CHAT_SERVER_TEAM';

export const BROADCAST_CHAT_SERVER_WHISPER = 'BROADCAST_CHAT_SERVER_WHISPER';

export const BROADCAST_CHAT_TEAM = 'BROADCAST_CHAT_TEAM';

export const BROADCAST_CHAT_WHISPER = 'BROADCAST_CHAT_WHISPER';

export const BROADCAST_EVENT_BOOST = 'BROADCAST_EVENT_BOOST';

export const BROADCAST_EVENT_BOUNCE = 'BROADCAST_EVENT_BOUNCE';

export const BROADCAST_EVENT_REPEL = 'BROADCAST_EVENT_REPEL';

export const BROADCAST_EVENT_STEALTH = 'BROADCAST_EVENT_STEALTH';

export const BROADCAST_FLAG_CAPTURED = 'BROADCAST_FLAG_CAPTURED';

export const BROADCAST_FLAG_RETURNED = 'BROADCAST_FLAG_RETURNED';

export const BROADCAST_FLAG_TAKEN = 'BROADCAST_FLAG_TAKEN';

export const BROADCAST_GAME_FIREWALL = 'BROADCAST_GAME_FIREWALL';

export const BROADCAST_GAME_FLAG = 'BROADCAST_GAME_FLAG';

export const BROADCAST_MOB_DESPAWN = 'BROADCAST_MOB_DESPAWN';

export const BROADCAST_MOB_DESPAWN_COORDS = 'BROADCAST_MOB_DESPAWN_COORDS';

export const BROADCAST_MOB_UPDATE = 'BROADCAST_MOB_UPDATE';

export const BROADCAST_MOB_UPDATE_STATIONARY = 'BROADCAST_MOB_UPDATE_STATIONARY';

export const BROADCAST_PLAYER_FIRE = 'BROADCAST_PLAYER_FIRE';

export const BROADCAST_PLAYER_FLAG = 'BROADCAST_PLAYER_FLAG';

export const BROADCAST_PLAYER_HIT = 'BROADCAST_PLAYER_HIT';

export const BROADCAST_PLAYER_KILL = 'BROADCAST_PLAYER_KILL';

export const BROADCAST_PLAYER_LEAVE = 'BROADCAST_PLAYER_LEAVE';

export const BROADCAST_PLAYER_LEVEL = 'BROADCAST_PLAYER_LEVEL';

export const BROADCAST_PLAYER_NEW = 'BROADCAST_PLAYER_NEW';

export const BROADCAST_PLAYER_RESPAWN = 'BROADCAST_PLAYER_RESPAWN';

export const BROADCAST_PLAYER_RETEAM = 'BROADCAST_PLAYER_RETEAM';

export const BROADCAST_PLAYER_TYPE = 'BROADCAST_PLAYER_TYPE';

export const BROADCAST_PLAYER_UPDATE = 'BROADCAST_PLAYER_UPDATE';

export const BROADCAST_PLAYERS_ALIVE = 'BROADCAST_PLAYERS_ALIVE';

export const BROADCAST_SCORE_BOARD = 'BROADCAST_SCORE_BOARD';

export const BROADCAST_SERVER_CUSTOM = 'BROADCAST_SERVER_CUSTOM';

export const BROADCAST_SERVER_MESSAGE = 'BROADCAST_SERVER_MESSAGE';
