export const COMMAND_DROP_FLAG = 'COMMAND_DROP_FLAG';

export const COMMAND_DROP_UPGRADE = 'COMMAND_DROP_UPGRADE';

export const COMMAND_ELECTIONS = 'COMMAND_ELECTIONS';

export const COMMAND_FLAG = 'COMMAND_FLAG';

export const COMMAND_HORIZON = 'COMMAND_HORIZON';

export const COMMAND_MATCH = 'COMMAND_MATCH';

export const COMMAND_PROFILE = 'COMMAND_PROFILE';

export const COMMAND_RESPAWN = 'COMMAND_RESPAWN';

export const COMMAND_SERVER = 'COMMAND_SERVER';

export const COMMAND_SPECTATE = 'COMMAND_SPECTATE';

export const COMMAND_SPECTATORS = 'COMMAND_SPECTATORS';

export const COMMAND_SU = 'COMMAND_SU';

export const COMMAND_SWITCH = 'COMMAND_SWITCH';

export const COMMAND_UPGRADE = 'COMMAND_UPGRADE';
