export const CONNECTIONS_CLOSE = 'CONNECTIONS_CLOSE';

export const CONNECTIONS_BAN_IP = 'CONNECTIONS_BAN_IP';

export const CONNECTIONS_DISCONNECT = 'CONNECTIONS_DISCONNECT';

export const CONNECTIONS_CHECK_PACKET_LIMITS = 'CONNECTIONS_CHECK_PACKET_LIMITS';

export const CONNECTIONS_CLOSED = 'CONNECTIONS_CLOSED';

export const CONNECTIONS_DISCONNECT_PLAYER = 'CONNECTIONS_DISCONNECT_PLAYER';

export const CONNECTIONS_FLUSH_BANS = 'CONNECTIONS_FLUSH_BANS';

export const CONNECTIONS_KICK = 'CONNECTIONS_KICK';

export const CONNECTIONS_PACKET_RECEIVED = 'CONNECTIONS_PACKET_RECEIVED';

export const CONNECTIONS_PLAYER_DISCONNECTED = 'CONNECTIONS_PLAYER_DISCONNECTED';

export const CONNECTIONS_SEND_PACKETS = 'CONNECTIONS_SEND_PACKETS';

export const CONNECTIONS_UNBAN_IP = 'CONNECTIONS_UNBAN_IP';
