export const ERRORS_AFK_DISCONNECT = 'ERRORS_AFK_DISCONNECT';

export const ERRORS_ALREADY_LOGGED_IN = 'ERRORS_ALREADY_LOGGED_IN';

export const ERRORS_INCORRECT_PROTOCOL = 'ERRORS_INCORRECT_PROTOCOL';

export const ERRORS_INVALID_LOGIN_DATA = 'ERRORS_INVALID_LOGIN_DATA';

export const ERRORS_NOT_ENOUGH_UPGRADES = 'ERRORS_NOT_ENOUGH_UPGRADES';

export const ERRORS_PACKET_DECODE_FAILED = 'ERRORS_PACKET_DECODE_FAILED';

export const ERRORS_PACKET_FLOODING_DETECTED = 'ERRORS_PACKET_FLOODING_DETECTED';

export const ERRORS_RESPAWN_INACTIVITY_HEALTH_REQUIRED =
  'ERRORS_RESPAWN_INACTIVITY_HEALTH_REQUIRED';

export const ERRORS_SPECTATE_INACTIVITY_HEALTH_REQUIRED =
  'ERRORS_SPECTATE_INACTIVITY_HEALTH_REQUIRED';
