export const SERVER_FRAMES_SKIPPED = 'SERVER_FRAMES_SKIPPED';

export const SERVER_UPDATE_SCALE_FACTOR = 'SERVER_UPDATE_SCALE_FACTOR';

export const SERVER_SHUTDOWN_STARTED = 'SERVER_SHUTDOWN_STARTED'