export const PLAYERS_ALIVE_UPDATE = 'PLAYERS_ALIVE_UPDATE';

export const PLAYERS_APPLY_INFERNO = 'PLAYERS_APPLY_INFERNO';

export const PLAYERS_APPLY_SHIELD = 'PLAYERS_APPLY_SHIELD';

export const PLAYERS_ASSIGN_ALIVE_STATUS = 'PLAYERS_ASSIGN_ALIVE_STATUS';

export const PLAYERS_ASSIGN_SPAWN_POSITION = 'PLAYERS_ASSIGN_SPAWN_POSITION';

export const PLAYERS_ASSIGN_TEAM = 'PLAYERS_ASSIGN_TEAM';

export const PLAYERS_BEFORE_REMOVE = 'PLAYERS_BEFORE_REMOVE';

export const PLAYERS_BOUNCE = 'PLAYERS_BOUNCE';

export const PLAYERS_CREATE = 'PLAYERS_CREATE';

export const PLAYERS_CREATED = 'PLAYERS_CREATED';

export const PLAYERS_EMIT_CHANNEL_CONNECT = 'PLAYERS_EMIT_CHANNEL_CONNECT';

export const PLAYERS_EMIT_CHANNEL_DISCONNECT = 'PLAYERS_EMIT_CHANNEL_DISCONNECT';

export const PLAYERS_EMIT_CHANNEL_FLAG = 'PLAYERS_EMIT_CHANNEL_FLAG';

export const PLAYERS_EMIT_CHANNEL_RESPAWN = 'PLAYERS_EMIT_CHANNEL_RESPAWN';

export const PLAYERS_HIT = 'PLAYERS_HIT';

export const PLAYERS_KICK = 'PLAYERS_KICK';

export const PLAYERS_KILL = 'PLAYERS_KILL';

export const PLAYERS_KILLED = 'PLAYERS_KILLED';

export const PLAYERS_LIMIT_REACHED = 'PLAYERS_LIMIT_REACHED';

export const PLAYERS_RANKINGS_SORT = 'PLAYERS_RANKINGS_SORT';

export const PLAYERS_RANKINGS_UPDATE = 'PLAYERS_RANKINGS_UPDATE';

export const PLAYERS_REMOVE = 'PLAYERS_REMOVE';

export const PLAYERS_REMOVED = 'PLAYERS_REMOVED';

export const PLAYERS_REPEL_ADD = 'PLAYERS_REPEL_ADD';

export const PLAYERS_REPEL_DELETE = 'PLAYERS_REPEL_DELETE';

export const PLAYERS_REPEL_MOBS = 'PLAYERS_REPEL_MOBS';

export const PLAYERS_REPEL_UPDATE = 'PLAYERS_REPEL_UPDATE';

export const PLAYERS_RESPAWN = 'PLAYERS_RESPAWN';

export const PLAYERS_RESPAWNED = 'PLAYERS_RESPAWNED';

export const PLAYERS_SET_NEW_HORIZON = 'PLAYERS_SET_NEW_HORIZON';

export const PLAYERS_SET_SHIP_TYPE = 'PLAYERS_SET_SHIP_TYPE';

export const PLAYERS_STATS_ANNOUNCE = 'PLAYERS_STATS_ANNOUNCE';

export const PLAYERS_SWITCHED_TO_SPECTATE = 'PLAYERS_SWITCHED_TO_SPECTATE';

export const PLAYERS_UPDATE = 'PLAYERS_UPDATE';

export const PLAYERS_UPDATE_FLAG = 'PLAYERS_UPDATE_FLAG';

export const PLAYERS_UPDATE_HORIZON = 'PLAYERS_UPDATE_HORIZON';

export const PLAYERS_UPDATE_TEAM = 'PLAYERS_UPDATE_TEAM';

export const PLAYERS_UPGRADES_RESET = 'PLAYERS_UPGRADES_RESET';
