export const POWERUPS_ADD_PERIODIC = 'POWERUPS_ADD_PERIODIC';

export const POWERUPS_DESPAWN = 'POWERUPS_DESPAWN';

export const POWERUPS_DESPAWNED = 'POWERUPS_DESPAWNED';

export const POWERUPS_PICKED = 'POWERUPS_PICKED';

export const POWERUPS_SPAWN = 'POWERUPS_SPAWN';

export const POWERUPS_UPDATE_CONFIG = 'POWERUPS_UPDATE_CONFIG';
