export const RESPONSE_BACKUP = 'RESPONSE_BACKUP';

export const RESPONSE_COMMAND_REPLY = 'RESPONSE_COMMAND_REPLY';

export const RESPONSE_EVENT_LEAVE_HORIZON = 'RESPONSE_EVENT_LEAVE_HORIZON';

export const RESPONSE_GAME_SPECTATE = 'RESPONSE_GAME_SPECTATE';

export const RESPONSE_LOGIN = 'RESPONSE_LOGIN';

export const RESPONSE_PING_RESULT = 'RESPONSE_PING_RESULT';

export const RESPONSE_PLAYER_BAN = 'RESPONSE_PLAYER_BAN';

export const RESPONSE_PLAYER_POWERUP = 'RESPONSE_PLAYER_POWERUP';

export const RESPONSE_PLAYER_UPGRADE = 'RESPONSE_PLAYER_UPGRADE';

export const RESPONSE_SCORE_DETAILED = 'RESPONSE_SCORE_DETAILED';

export const RESPONSE_SCORE_UPDATE = 'RESPONSE_SCORE_UPDATE';

export const RESPONSE_SEND_PING = 'RESPONSE_SEND_PING';

export const RESPONSE_SERVER_MESSAGE = 'RESPONSE_SERVER_MESSAGE';

export const RESPONSE_SERVER_PLAYER_CONNECT = 'RESPONSE_SERVER_PLAYER_CONNECT';

export const RESPONSE_SPECTATE_KILL = 'RESPONSE_SPECTATE_KILL';

export const RESPONSE_VOTEMUTE_PASSED = 'RESPONSE_VOTEMUTE_PASSED';

export const RESPONSE_VOTEMUTED = 'RESPONSE_VOTEMUTED';
