export const SPECTATE_EMIT_CHANNEL_EVENTS = 'SPECTATE_EMIT_CHANNEL_EVENTS';

export const SPECTATE_ENTER_MODE = 'SPECTATE_ENTER_MODE';

export const SPECTATE_NEXT = 'SPECTATE_NEXT';

export const SPECTATE_PLAYER = 'SPECTATE_PLAYER';

export const SPECTATE_PREV = 'SPECTATE_PREV';
