export const SYNC_ENQUEUE_UPDATE = 'SYNC_ENQUEUE_UPDATE';

export const SYNC_SUBSCRIBE = 'SYNC_SUBSCRIBE';

export const SYNC_UNSUBSCRIBE = 'SYNC_UNSUBSCRIBE';

export const SYNC_CONNECTION_INACTIVE = 'SYNC_CONNECTION_INACTIVE';
