export const TIMELINE_BEFORE_GAME_START = 'TIMELINE_BEFORE_GAME_START';

export const TIMELINE_GAME_START = 'TIMELINE_GAME_START';

export const TIMELINE_GAME_MATCH_START = 'TIMELINE_GAME_MATCH_START';

export const TIMELINE_LOOP_START = 'TIMELINE_LOOP_START';

export const TIMELINE_LOOP_END = 'TIMELINE_LOOP_END';

export const TIMELINE_LOOP_TICK = 'TIMELINE_LOOP_TICK';

export const TIMELINE_CLOCK_SECOND = 'TIMELINE_CLOCK_SECOND';

export const TIMELINE_CLOCK_MINUTE = 'TIMELINE_CLOCK_MINUTE';

export const TIMELINE_CLOCK_HOUR = 'TIMELINE_CLOCK_HOUR';

export const TIMELINE_CLOCK_DAY = 'TIMELINE_CLOCK_DAY';
