export const USERS_WORKER_SAVE_STATS = 'USERS_WORKER_SAVE_STATS';

export const USERS_WORKER_SAVE_STATS_RESPONSE = 'USERS_WORKER_SAVE_STATS_RESPONSE';

export const USERS_WORKER_STARTED = 'USERS_WORKER_STARTED';

export const USERS_WORKER_STOP = 'USERS_WORKER_STOP';
