export const VIEWPORTS_CREATE = 'VIEWPORTS_CREATE';

export const VIEWPORTS_REMOVE = 'VIEWPORTS_REMOVE';

export const VIEWPORTS_UPDATE_HORIZON = 'VIEWPORTS_UPDATE_HORIZON';

export const VIEWPORTS_UPDATE_POSITION = 'VIEWPORTS_UPDATE_POSITION';
