export const WORKERS_LOG_DEBUG = 'WORKERS_LOG_DEBUG';

export const WORKERS_LOG_ERROR = 'WORKERS_LOG_ERROR';

export const WORKERS_LOG_FATAL = 'WORKERS_LOG_FATAL';

export const WORKERS_LOG_INFO = 'WORKERS_LOG_INFO';

export const WORKERS_LOG_WARN = 'WORKERS_LOG_WARN';
