export const WS_WORKER_CONNECTION_OPENED = 'WS_WORKER_CONNECTION_OPENED';

export const WS_WORKER_GET_PLAYER = 'WS_WORKER_GET_PLAYER';

export const WS_WORKER_GET_PLAYER_RESPONSE = 'WS_WORKER_GET_PLAYER_RESPONSE';

export const WS_WORKER_GET_PLAYERS_LIST = 'WS_WORKER_GET_PLAYERS_LIST';

export const WS_WORKER_GET_PLAYERS_LIST_RESPONSE = 'WS_WORKER_GET_PLAYERS_LIST_RESPONSE';

export const WS_WORKER_SEND_PACKETS = 'WS_WORKER_SEND_PACKETS';

export const WS_WORKER_STARTED = 'WS_WORKER_STARTED';

export const WS_WORKER_STOP = 'WS_WORKER_STOP';

export const WS_WORKER_UPDATE_PLAYERS_AMOUNT = 'WS_WORKER_UPDATE_PLAYERS_AMOUNT';
