export const CHANNEL_CHAT = 'CHANNEL_CHAT';

export const CHANNEL_CONNECT_PLAYER = 'CHANNEL_CONNECT_PLAYER';

export const CHANNEL_DEFAULT = 'CHANNEL_DEFAULT';

export const CHANNEL_DISCONNECT_PLAYER = 'CHANNEL_DISCONNECT_PLAYER';

export const CHANNEL_MUTE = 'CHANNEL_MUTE';

export const CHANNEL_PLAYERS_STATS = 'CHANNEL_PLAYERS_STATS';

export const CHANNEL_RESPAWN_PLAYER = 'CHANNEL_RESPAWN_PLAYER';

export const CHANNEL_SPECTATE = 'CHANNEL_SPECTATE';

export const CHANNEL_UPDATE_HORIZON = 'CHANNEL_UPDATE_HORIZON';

export const CHANNEL_UPDATE_PLAYER_FLAG = 'CHANNEL_UPDATE_PLAYER_FLAG';
